### PR TITLE
Add newer options

### PR DESCRIPTION
**Pull request by mgrebenets**
Add 46 new uncrustify configuration options from version 0.61

### CODE REVIEW

**Comment by mgrebenets** [comment]
bump

@ryanmaxwell are there concerns with this PR? It's been sitting there for quite a while now.

**Comment by ryanmaxwell** [comment]
Sorry been wanting to pull this in, but I'm away overseas with no computer until the new year, I'll aim to get to it in Jan!

**Comment by mgrebenets** [comment]
Cool! No rush :+1: I just wasn't sure if it was going anywhere :)

**Comment by ryanmaxwell** [comment]
@dzenbot No prob. How did you find the diffs between 0.6 and 0.61? Just manually? I used to have a script that did it for me but i've misplaced it :/

**Comment by mgrebenets** [comment]
Same here. I couldn't even find the 0.61 config I refereed to as "latest" while making the changes... can't even google it up now... It would be nice to have such an option in `oclint` itself, to spit out config file with _all_ the possible rules in it.

**Comment by ryanmaxwell** [comment]
I guess watching https://github.com/bengardner/uncrustify/commits/master/src/options.h is also a good way to go about diffs!

**Comment by ryanmaxwell** [comment]
I've found 2 new options and added them in. I'll tag release a new version tonight.

**Pull request merged**
